# ----------------------------------------------------
# Theme
# ----------------------------------------------------

theme = "catppuccin_mocha"

# ----------------------------------------------------
# Editor
# ----------------------------------------------------

[editor]
continue-comments = false
completion-replace = true
true-color = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.statusline]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left   = ["mode", "spinner"]
center = ["file-name"]
right  = ["diagnostics", "version-control"]
diagnostics = ["warning", "error", "info"]

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker] 
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 25
wrap-indicator = "↪ "
wrap-at-text-width = false

[editor.inline-diagnostics]
other-lines = "info"
cursor-line = "warning"

# ----------------------------------------------------
# Keybidings
# ----------------------------------------------------

[keys.normal]
C-q = ":q!"
del = ":buffer-close!"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
q      = ":q"
space  = ":w"  
p = ":sh tmux send-keys -t {down-of} 'clear && python %{buffer_name}' Enter"

