[[mgr.append_keymap]]
on = ["g", "t"]
run = "cd ~/.local/share/Trash/files/"

[[mgr.append_keymap]]
on = ["g", "."]
run = "cd ~/.dotfiles"

[[mgr.append_keymap]]
on = ["g", "p"]
run = "cd ~/projects"

[[mgr.append_keymap]]
on = ["g", "w"]
run = "cd ~/work"

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd back to the root of the current Git repository"
