[services.fcos]
type = "sftp"
host = "192.168.1.226"
user = "core"
port = 22
key_file = "~/.ssh/id_ed25519"

[services.router]
type = "sftp"
host = "192.168.1.1"
user = "root"
port = 22
key_file = "~/.ssh/id_ed25519"
